version: '3.7'

services:
    db:
        container_name: godb
        image: postgis/postgis:13-3.1
        ports:
            - 54300:5432
        volumes:
            - 'database:/var/lib/postgresql/data'
        tty: true
        environment:
            POSTGRES_DB: godb
            POSTGRES_USER: godb
            POSTGRES_PASSWORD: godb

volumes:
    database:
